image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - test
  - package
  - deploy

gradlew-test:
  image: openjdk:8
  stage: test
  script:
    - ./gradlew test -i

docker-build:
  stage: package
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker build -t registry.gitlab.com/sotomski/api/image .
  - docker push registry.gitlab.com/sotomski/api/image

deploy-staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: https://staging.example.com
  only:
  - develop
  - master
