image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci
  # Application deployment domain
  KUBE_DOMAIN: ruby-openshift-example.tanukionline.com

stages:
  - test
  - package
  - deploy

gradlew-test:
  image: openjdk:8
  stage: test
  script:
    - ./gradlew test -i

docker-build:
  stage: package
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker build -t registry.gitlab.com/sotomski/api/image .
  - docker push registry.gitlab.com/sotomski/api/image

staging:
  image: registry.gitlab.com/gitlab-examples/openshift-deploy
  stage: deploy
  variables:
    CI_ENVIRONMENT_URL: http://${CI_ENVIRONMENT_SLUG}.starter-us-west-2.openshift.com
  script:
    - command deploy
  environment:
    name: staging
    url: http://$CI_ENVIRONMENT_SLUG.starter-us-west-2.openshift.com
