version: '2'
services:
#  api:
#    build: .
#    ports:
#     - "8080:8080"
#    volumes:
#     - .:/code
#  postgres:
#    image: "postgres:9.6"
#    ports:
#     - "5432:5432"
  mailhog:
    image: "mailhog/mailhog"
    ports:
     - "1025:1025"
     - "8025:8025"
